name: Tests
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15      
      - name: Check out source code
        uses: actions/checkout@v1
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false      
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .
      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v
      - name: TestSLOs
        env:
          GOPROXY: "https://proxy.golang.org"
          TF_ACC: true
          DYNATRACE_DEBUG: true
          DYNATRACE_ENV_URL: ${{ secrets.DYNATRACE_ENV_URL }}
          DYNATRACE_API_TOKEN: ${{ secrets.DYNATRACE_API_TOKEN }}
        run: go test -v github.com/dynatrace-oss/terraform-provider-dynatrace/resources/slo                